apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mjne
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-vhjl-tenant/byoc-app-ruik/mjne@sha256:df03ffb789d76a1ad9f1f27c3e3ffec41de3b32fb41cbe2c6ee2c81ee68fe5bd
        name: my-java-quarkus
        resources: {}
status: {}
