apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mjne
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mjne
    app.kubernetes.io/part-of: byoc-app-ruik
  name: mjneaduj
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: mjne
    weight: null
status: {}
